# Generated by Django 4.2.7 on 2023-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('cast', models.TextField()),
                ('genres', models.TextField()),
                ('imdb_link', models.URLField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
